# Generated by Django 3.1.1 on 2021-01-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0002_checkout_order_orderitem_product_reviews_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FR', 'Fruits'), ('VG', 'Vegetables'), ('MT', 'Meat'), ('JU', 'Juices'), ('TU', 'Tubers'), ('DY', 'Dairy')], default='FR', max_length=2),
        ),
    ]
