# Generated by Django 3.1.1 on 2021-01-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0003_auto_20210109_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FR', 'Fruits'), ('VG', 'Vegetables'), ('MT', 'Meat'), ('GR', 'Grains'), ('TU', 'Tubers'), ('DY', 'Dairy')], default='FR', max_length=2),
        ),
    ]
