# Generated by Django 3.1.1 on 2021-01-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0004_auto_20210109_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
