# Generated by Django 3.1.1 on 2021-01-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0009_auto_20210118_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='cost',
        ),
    ]
