# Generated by Django 3.1.1 on 2021-02-08 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0011_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
